# KEGG Pathway Visualization Shiny App
# Author: Generated by GitHub Copilot
# Date: 2025-08-04

# Load required libraries
library(shiny)
library(shinydashboard)
library(visNetwork)
library(DT)
library(KEGGREST)
library(KEGGgraph)
library(dplyr)
library(plotly)
library(shinyWidgets)

# Install and load biomaRt if not available
if (!requireNamespace("biomaRt", quietly = TRUE)) {
    if (!requireNamespace("BiocManager", quietly = TRUE)) {
        install.packages("BiocManager")
    }
    BiocManager::install("biomaRt")
}
library(biomaRt)

# Install xml2 for KEGG coordinate extraction
if (!requireNamespace("xml2", quietly = TRUE)) {
    install.packages("xml2")
}
library(xml2)

# Install myTAI for phylostratum coloring (optional)
if (!requireNamespace("myTAI", quietly = TRUE)) {
    message("myTAI package not found. Installing for phylostratum coloring...")
    install.packages("myTAI")
}
# Note: myTAI is loaded conditionally in the phylostratum functions

# Source utility functions
source("R/kegg_utils.R")
source("R/network_utils.R")
