# KEGG Pathway Visualization Shiny App
# Author: Generated by GitHub Copilot
# Date: 2025-08-04

# Load required libraries
library(shiny)
library(shinydashboard)
library(visNetwork)
library(DT)
library(KEGGREST)
library(KEGGgraph)
library(dplyr)
library(plotly)
library(shinyWidgets)
library(ggplot2)
library(scales)  # Required for PS_colours function

# Install and load biomaRt if not available
if (!requireNamespace("biomaRt", quietly = TRUE)) {
    cat("Installing biomaRt...\n")
    BiocManager::install("biomaRt", ask = FALSE, update = FALSE)
}
library(biomaRt)

# Install xml2 for KEGG coordinate extraction
if (!requireNamespace("xml2", quietly = TRUE)) {
    install.packages("xml2")
}
library(xml2)

# Install BiocManager first
if (!requireNamespace("BiocManager", quietly = TRUE)) {
    install.packages("BiocManager")
}

# Install required Bioconductor packages for enrichment analysis
required_bioc_packages <- c("clusterProfiler", "org.Hs.eg.db", "DOSE")
for (pkg in required_bioc_packages) {
    if (!requireNamespace(pkg, quietly = TRUE)) {
        cat("Installing", pkg, "...\n")
        BiocManager::install(pkg, ask = FALSE, update = FALSE)
    }
}

# Check and install myTAI if needed
if (!requireNamespace("myTAI", quietly = TRUE)) {
    cat("Installing myTAI...\n")
    BiocManager::install("myTAI", ask = FALSE, update = FALSE)
}

# Install additional CRAN dependencies that might be needed
required_cran_packages <- c("igraph", "tidyr", "stringr")
for (pkg in required_cran_packages) {
    if (!requireNamespace(pkg, quietly = TRUE)) {
        cat("Installing", pkg, "...\n")
        install.packages(pkg)
    }
}

# Load the packages
library(clusterProfiler)
library(org.Hs.eg.db)

# Source utility functions
source("R/kegg_utils.R")
source("R/network_utils.R")
source("R/enrichment_utils.R")
source("R/evolutionary_utils.R")

# Pre-compute global phylostratum color palette for consistency
# This ensures phylostratum 1 is always black regardless of how many strata are present
GLOBAL_PHYLOSTRATA_COLORS <- {
    max_strata <- 28  # Maximum number of phylostrata
    vals <- 1:max_strata |>
        log() |>
        scales::rescale()
   
    pal <- grDevices::colorRampPalette(c("black", "#AD6F3B", "lightgreen"))
    full_palette <- pal(100)[floor(vals * 99) + 1]
    
    # Create named vector for easy access
    setNames(full_palette, 1:max_strata)
}

# Note: Gene mapping data is loaded on-demand to improve startup speed
